package JFrame;


import Costs.*;
import Revenues.*;
import java.sql.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dpw82
 */
public class AccountingJFrame extends javax.swing.JFrame {
    
    static final String DB_URL = "jdbc:mysql://localhost/AccountingJFrame";
    static final String USER = "guest";
    static final String PASS = "guest123";

    /**
     * Creates new form Driver
     */
    public AccountingJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        VINbutton = new javax.swing.JButton();
        makeButton = new javax.swing.JButton();
        payRateButton = new javax.swing.JButton();
        jobHoursButton = new javax.swing.JButton();
        CleaningCostbutton = new javax.swing.JButton();
        techCostButton = new javax.swing.JButton();
        monthlyRentButton = new javax.swing.JButton();
        yearlyRentButton = new javax.swing.JButton();
        salesTaxButton = new javax.swing.JButton();
        propertyTaxButton = new javax.swing.JButton();
        modelButton = new javax.swing.JButton();
        priceButton = new javax.swing.JButton();
        jobTitlebutton = new javax.swing.JButton();
        officeCostButton = new javax.swing.JButton();
        stateTaxButton = new javax.swing.JButton();
        federalTaxButton = new javax.swing.JButton();
        salePrice = new javax.swing.JButton();
        carNameButton = new javax.swing.JButton();
        CustomEmployeeConstructor = new javax.swing.JButton();
        AddEmployee = new javax.swing.JButton();
        addTax = new javax.swing.JButton();
        AddCar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        caclExpensesMisc = new javax.swing.JButton();
        calcExpenses = new javax.swing.JButton();
        calcExpensesTax = new javax.swing.JButton();
        createSale = new javax.swing.JButton();
        carVINtext = new javax.swing.JTextField();
        carMakeText = new javax.swing.JTextField();
        carModelText = new javax.swing.JTextField();
        carPriceText = new javax.swing.JTextField();
        EmployeeNameText = new javax.swing.JTextField();
        payRateText = new javax.swing.JTextField();
        hoursText = new javax.swing.JTextField();
        employeeTitleText = new javax.swing.JTextField();
        cleaningCostText = new javax.swing.JTextField();
        techCostField = new javax.swing.JTextField();
        officeCostField = new javax.swing.JTextField();
        monthlyRentText = new javax.swing.JTextField();
        yearlyRentText = new javax.swing.JTextField();
        salesTaxField = new javax.swing.JTextField();
        propertyTaxField = new javax.swing.JTextField();
        federalTaxField = new javax.swing.JTextField();
        stateTaxText = new javax.swing.JTextField();
        priceSoldText = new javax.swing.JTextField();
        carNameSoldText = new javax.swing.JTextField();
        CalcTotalSales = new javax.swing.JButton();
        calcGrandTotExpenses = new javax.swing.JButton();
        NetProfit = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VINbutton.setText("VIN");
        VINbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VINbuttonActionPerformed(evt);
            }
        });

        makeButton.setText("Make");
        makeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeButtonActionPerformed(evt);
            }
        });

        payRateButton.setText("payRate");
        payRateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payRateButtonActionPerformed(evt);
            }
        });

        jobHoursButton.setText("hours");

        CleaningCostbutton.setText("cleaningCost");

        techCostButton.setText("techCost");

        monthlyRentButton.setText("monthlyRent");

        yearlyRentButton.setText("yearlyRent");
        yearlyRentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearlyRentButtonActionPerformed(evt);
            }
        });

        salesTaxButton.setText("salesTax");

        propertyTaxButton.setText("propertyTax");

        modelButton.setText("Model");
        modelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelButtonActionPerformed(evt);
            }
        });

        priceButton.setText("Price");
        priceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceButtonActionPerformed(evt);
            }
        });

        jobTitlebutton.setText("title");
        jobTitlebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobTitlebuttonActionPerformed(evt);
            }
        });

        officeCostButton.setText("officeCost");

        stateTaxButton.setText("stateTax");

        federalTaxButton.setText("federalTax");

        salePrice.setText("Sale Price");

        carNameButton.setText("Car Name");

        CustomEmployeeConstructor.setText("Employee Name");
        CustomEmployeeConstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomEmployeeConstructorActionPerformed(evt);
            }
        });

        AddEmployee.setText("Add Employee");

        addTax.setText("Add Tax");

        AddCar.setText("Add Car");
        AddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCarActionPerformed(evt);
            }
        });

        jButton5.setText("Calc Expenses");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("calc Expenses");

        caclExpensesMisc.setText("calc Expenses");

        calcExpenses.setText("calc Expenses");

        calcExpensesTax.setText("calc Expenses");

        createSale.setText("Create Sale");

        carVINtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carVINtextActionPerformed(evt);
            }
        });

        CalcTotalSales.setText("Calculate Total Sales");
        CalcTotalSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcTotalSalesActionPerformed(evt);
            }
        });

        calcGrandTotExpenses.setText("Calculate Total Expenses ");

        NetProfit.setText("Calcuate Net Profit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(VINbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(makeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(monthlyRentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearlyRentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yearlyRentText)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(CleaningCostbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(cleaningCostText))
                                .addGap(33, 33, 33)
                                .addComponent(techCostButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(salesTaxButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(salePrice))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(salesTaxField)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(propertyTaxField)
                                    .addComponent(carNameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(propertyTaxButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(carNameSoldText))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(calcExpenses)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(createSale)
                                                .addGap(35, 35, 35)
                                                .addComponent(CalcTotalSales)
                                                .addGap(18, 18, 18)
                                                .addComponent(calcGrandTotExpenses)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(federalTaxField)
                                            .addComponent(federalTaxButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(stateTaxText)
                                            .addComponent(stateTaxButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(23, 23, 23)
                                        .addComponent(addTax, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(calcExpensesTax, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(88, 88, 88))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(modelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(hoursText, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(employeeTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(officeCostField)
                                            .addComponent(officeCostButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(caclExpensesMisc)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(NetProfit)
                        .addGap(210, 210, 210))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(techCostField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(CustomEmployeeConstructor)
                                                    .addComponent(EmployeeNameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(17, 17, 17)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(payRateButton)
                                                    .addComponent(payRateText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(27, 27, 27)
                                        .addComponent(jobHoursButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(carVINtext, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(carMakeText, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(carModelText, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(carPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jobTitlebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(priceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(10, 10, 10)
                                                .addComponent(AddCar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton5)
                                            .addComponent(jButton6)))))
                            .addComponent(monthlyRentText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceSoldText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(carVINtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(carMakeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(carModelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(carPriceText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VINbutton)
                    .addComponent(makeButton)
                    .addComponent(modelButton)
                    .addComponent(priceButton)
                    .addComponent(AddCar)
                    .addComponent(jButton5))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payRateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payRateButton)
                    .addComponent(jobHoursButton)
                    .addComponent(jobTitlebutton)
                    .addComponent(CustomEmployeeConstructor)
                    .addComponent(AddEmployee)
                    .addComponent(jButton6))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cleaningCostText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(techCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(officeCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CleaningCostbutton)
                    .addComponent(techCostButton)
                    .addComponent(officeCostButton)
                    .addComponent(caclExpensesMisc))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthlyRentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearlyRentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthlyRentButton)
                    .addComponent(yearlyRentButton)
                    .addComponent(calcExpenses))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salesTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propertyTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(federalTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stateTaxText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(salesTaxButton)
                        .addComponent(propertyTaxButton))
                    .addComponent(federalTaxButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stateTaxButton)
                        .addComponent(addTax)
                        .addComponent(calcExpensesTax)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceSoldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carNameSoldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salePrice)
                    .addComponent(carNameButton)
                    .addComponent(createSale)
                    .addComponent(CalcTotalSales)
                    .addComponent(calcGrandTotExpenses)
                    .addComponent(NetProfit))
                .addContainerGap(1057, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VINbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VINbuttonActionPerformed
        int numberIn = Integer.parseInt(carVINtext.getText());
        carVINtext.setText(" " + numberIn);
        
    }//GEN-LAST:event_VINbuttonActionPerformed

    private void makeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makeButtonActionPerformed

    private void modelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelButtonActionPerformed

    private void jobTitlebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobTitlebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobTitlebuttonActionPerformed

    private void yearlyRentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearlyRentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearlyRentButtonActionPerformed

    private void payRateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payRateButtonActionPerformed
        int numberIn = Integer.parseInt(payRateText.getText());
        payRateText.setText("" + numberIn);
    }//GEN-LAST:event_payRateButtonActionPerformed

    private void CustomEmployeeConstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomEmployeeConstructorActionPerformed
        Employee employee = new Employee(EmployeeNameText.getText());
        EmployeeNameText.setText(employee.getEmployeeName() + " name is set");
    }//GEN-LAST:event_CustomEmployeeConstructorActionPerformed

    private void priceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceButtonActionPerformed
        String carName = priceButton.getText();
        priceButton.setText(carName + " name is set.");
    }//GEN-LAST:event_priceButtonActionPerformed

    private void carVINtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carVINtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carVINtextActionPerformed

    private void AddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCarActionPerformed
        
    }//GEN-LAST:event_AddCarActionPerformed

    private void CalcTotalSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcTotalSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalcTotalSalesActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       try {
            Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
            Statement stmt = conn.createStatement();		      
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
              
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountingJFrame().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCar;
    private javax.swing.JButton AddEmployee;
    private javax.swing.JButton CalcTotalSales;
    private javax.swing.JButton CleaningCostbutton;
    private javax.swing.JButton CustomEmployeeConstructor;
    private javax.swing.JTextField EmployeeNameText;
    private javax.swing.JButton NetProfit;
    private javax.swing.JButton VINbutton;
    private javax.swing.JButton addTax;
    private javax.swing.JButton caclExpensesMisc;
    private javax.swing.JButton calcExpenses;
    private javax.swing.JButton calcExpensesTax;
    private javax.swing.JButton calcGrandTotExpenses;
    private javax.swing.JTextField carMakeText;
    private javax.swing.JTextField carModelText;
    private javax.swing.JButton carNameButton;
    private javax.swing.JTextField carNameSoldText;
    private javax.swing.JTextField carPriceText;
    private javax.swing.JTextField carVINtext;
    private javax.swing.JTextField cleaningCostText;
    private javax.swing.JButton createSale;
    private javax.swing.JTextField employeeTitleText;
    private javax.swing.JButton federalTaxButton;
    private javax.swing.JTextField federalTaxField;
    private javax.swing.JTextField hoursText;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jobHoursButton;
    private javax.swing.JButton jobTitlebutton;
    private javax.swing.JButton makeButton;
    private javax.swing.JButton modelButton;
    private javax.swing.JButton monthlyRentButton;
    private javax.swing.JTextField monthlyRentText;
    private javax.swing.JButton officeCostButton;
    private javax.swing.JTextField officeCostField;
    private javax.swing.JButton payRateButton;
    private javax.swing.JTextField payRateText;
    private javax.swing.JButton priceButton;
    private javax.swing.JTextField priceSoldText;
    private javax.swing.JButton propertyTaxButton;
    private javax.swing.JTextField propertyTaxField;
    private javax.swing.JButton salePrice;
    private javax.swing.JButton salesTaxButton;
    private javax.swing.JTextField salesTaxField;
    private javax.swing.JButton stateTaxButton;
    private javax.swing.JTextField stateTaxText;
    private javax.swing.JButton techCostButton;
    private javax.swing.JTextField techCostField;
    private javax.swing.JButton yearlyRentButton;
    private javax.swing.JTextField yearlyRentText;
    // End of variables declaration//GEN-END:variables
}