package JFrame;


import Costs.*;
import Revenues.*;
import java.sql.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dpw82
 */
public class AccountingJFrame extends javax.swing.JFrame {
    
    static final String DB_URL = "jdbc:mysql://localhost/TUTORIALSPOINT";
    static final String USER = "guest";
    static final String PASS = "guest123";

    /**
     * Creates new form Driver
     */
    public AccountingJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        SUVcost = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        SuvText = new java.awt.TextField();
        SportText = new java.awt.TextField();
        SEDANtext = new java.awt.TextField();
        CarNameText = new java.awt.TextField();
        hoursText = new java.awt.TextField();
        payRateButton = new javax.swing.JButton();
        jobHoursButton = new javax.swing.JButton();
        payRateText = new java.awt.TextField();
        jobTitletext = new java.awt.TextField();
        techCostText = new java.awt.TextField();
        CleaningCostbutton = new javax.swing.JButton();
        officeCostText = new java.awt.TextField();
        CleaningCostText = new java.awt.TextField();
        techCostButton = new javax.swing.JButton();
        monthlyRentButton = new javax.swing.JButton();
        yearlyRentText = new java.awt.TextField();
        yearlyRentButton = new javax.swing.JButton();
        monthlyRentText = new java.awt.TextField();
        salesTaxButton = new javax.swing.JButton();
        propertyTaxText = new java.awt.TextField();
        propertyTaxButton = new javax.swing.JButton();
        federalTaxText = new java.awt.TextField();
        salesTaxText = new java.awt.TextField();
        sportsPriceField = new java.awt.TextField();
        sportsNameField = new java.awt.TextField();
        SportCost = new javax.swing.JButton();
        CarName = new javax.swing.JButton();
        jobTitlebutton = new javax.swing.JButton();
        officeCostButton = new javax.swing.JButton();
        stateTaxButton = new javax.swing.JButton();
        federalTaxButton = new javax.swing.JButton();
        sportsPriceButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        CustomEmployeeConstructor = new javax.swing.JButton();
        employeeNameTextField = new java.awt.TextField();
        stateText = new javax.swing.JTextField();
        sportsconstructor = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Sedanconstructor = new javax.swing.JButton();
        SUVconstructor = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SUVcost.setText("SUVcost");
        SUVcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUVcostActionPerformed(evt);
            }
        });

        jButton2.setText("SEDANcost");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        SuvText.setText("textField1");
        SuvText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuvTextActionPerformed(evt);
            }
        });

        SportText.setText("textField2");
        SportText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportTextActionPerformed(evt);
            }
        });

        SEDANtext.setText("textField2");
        SEDANtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEDANtextActionPerformed(evt);
            }
        });

        CarNameText.setText("textField2");

        hoursText.setText("textField2");

        payRateButton.setText("payRate");
        payRateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payRateButtonActionPerformed(evt);
            }
        });

        jobHoursButton.setText("hours");

        payRateText.setText("textField1");

        jobTitletext.setText("textField2");

        techCostText.setText("textField2");

        CleaningCostbutton.setText("cleaningCost");

        officeCostText.setText("textField2");

        CleaningCostText.setText("textField1");
        CleaningCostText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleaningCostTextActionPerformed(evt);
            }
        });

        techCostButton.setText("techCost");

        monthlyRentButton.setText("monthlyRent");

        yearlyRentText.setText("textField2");

        yearlyRentButton.setText("yearlyRent");
        yearlyRentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearlyRentButtonActionPerformed(evt);
            }
        });

        monthlyRentText.setText("textField1");
        monthlyRentText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyRentTextActionPerformed(evt);
            }
        });

        salesTaxButton.setText("salesTax");

        propertyTaxText.setText("textField2");

        propertyTaxButton.setText("propertyTax");

        federalTaxText.setText("textField2");
        federalTaxText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                federalTaxTextActionPerformed(evt);
            }
        });
        federalTaxText.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                federalTaxTextTextValueChanged(evt);
            }
        });

        salesTaxText.setText("textField1");

        sportsPriceField.setText("textField1");
        sportsPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsPriceFieldActionPerformed(evt);
            }
        });

        sportsNameField.setText("textField2");

        SportCost.setText("SPORTcost");
        SportCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportCostActionPerformed(evt);
            }
        });

        CarName.setText("CarName");
        CarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarNameActionPerformed(evt);
            }
        });

        jobTitlebutton.setText("title");
        jobTitlebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobTitlebuttonActionPerformed(evt);
            }
        });

        officeCostButton.setText("officeCost");

        stateTaxButton.setText("stateTax");

        federalTaxButton.setText("federalTax");

        sportsPriceButton.setText("sportsPrice");

        jButton3.setText("sportsName");

        CustomEmployeeConstructor.setText("Employee");
        CustomEmployeeConstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomEmployeeConstructorActionPerformed(evt);
            }
        });

        employeeNameTextField.setText("textField1");

        sportsconstructor.setText("Create Sports");
        sportsconstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsconstructorActionPerformed(evt);
            }
        });

        jButton4.setText("Create Employee");

        jButton5.setText("jButton5");

        jButton6.setText("jButton6");

        jButton7.setText("jButton7");

        jButton8.setText("jButton8");

        Sedanconstructor.setText("Create Sedan");
        Sedanconstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SedanconstructorActionPerformed(evt);
            }
        });

        SUVconstructor.setText("Create SUV");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SUVconstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sportsconstructor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Sedanconstructor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(monthlyRentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(yearlyRentButton))
                                    .addComponent(monthlyRentText, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salesTaxText, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sportsPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CleaningCostText, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CleaningCostbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(techCostButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(techCostText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(yearlyRentText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(propertyTaxText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sportsNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(SuvText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(SUVcost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(SEDANtext, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(salesTaxButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(sportsPriceButton)
                                                .addGap(31, 31, 31)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton3)
                                            .addComponent(propertyTaxButton))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(officeCostText, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(SportCost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(SportText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(officeCostButton)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(federalTaxText, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(federalTaxButton))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(stateTaxButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CustomEmployeeConstructor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(employeeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(payRateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(payRateText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(27, 27, 27)
                                            .addComponent(jobHoursButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(hoursText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(CarNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(CarName)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jobTitlebutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jobTitletext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(SUVconstructor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(SEDANtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SuvText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Sedanconstructor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SUVcost)
                            .addComponent(jButton2)
                            .addComponent(SportCost)
                            .addComponent(sportsconstructor)))
                    .addComponent(CarName)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SportText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CarNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jobTitletext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hoursText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(payRateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(employeeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payRateButton)
                            .addComponent(jobHoursButton)
                            .addComponent(jobTitlebutton)
                            .addComponent(CustomEmployeeConstructor)
                            .addComponent(jButton4))))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(techCostText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CleaningCostText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CleaningCostbutton)
                                    .addComponent(techCostButton)
                                    .addComponent(officeCostButton)
                                    .addComponent(jButton5)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(officeCostText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yearlyRentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthlyRentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monthlyRentButton)
                            .addComponent(yearlyRentButton)
                            .addComponent(jButton6))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(propertyTaxText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salesTaxText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(salesTaxButton)
                                    .addComponent(propertyTaxButton)
                                    .addComponent(jButton7)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(federalTaxText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(federalTaxButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(stateTaxButton)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sportsNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sportsPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sportsPriceButton)
                    .addComponent(jButton3)
                    .addComponent(jButton8))
                .addContainerGap(1037, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CleaningCostTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleaningCostTextActionPerformed
        int numberIn = Integer.parseInt(payRateText.getText());
        payRateText.setText(" " + numberIn);
    }//GEN-LAST:event_CleaningCostTextActionPerformed

    private void SUVcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUVcostActionPerformed
        int numberIn = Integer.parseInt(SuvText.getText());
        SuvText.setText(" " + numberIn);
        
    }//GEN-LAST:event_SUVcostActionPerformed

    private void SEDANtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEDANtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEDANtextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SportTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportTextActionPerformed
        //// TODO add your handling code here:
    }//GEN-LAST:event_SportTextActionPerformed

    private void SportCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SportCostActionPerformed

    private void jobTitlebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobTitlebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobTitlebuttonActionPerformed

    private void yearlyRentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearlyRentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearlyRentButtonActionPerformed

    private void monthlyRentTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyRentTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthlyRentTextActionPerformed

    private void payRateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payRateButtonActionPerformed
        int numberIn = Integer.parseInt(payRateText.getText());
        payRateText.setText("" + numberIn);
    }//GEN-LAST:event_payRateButtonActionPerformed

    private void sportsPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sportsPriceFieldActionPerformed

    private void SuvTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuvTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SuvTextActionPerformed

    private void CustomEmployeeConstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomEmployeeConstructorActionPerformed
        Employee employee = new Employee(employeeNameTextField.getText());
        employeeNameTextField.setText(employee.getEmployeeName() + " name is set");
    }//GEN-LAST:event_CustomEmployeeConstructorActionPerformed

    private void CarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarNameActionPerformed
        String carName = CarNameText.getText();
        CarNameText.setText(carName + " name is set.");
    }//GEN-LAST:event_CarNameActionPerformed

    private void federalTaxTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_federalTaxTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_federalTaxTextActionPerformed

    private void sportsconstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsconstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sportsconstructorActionPerformed

    private void SedanconstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SedanconstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SedanconstructorActionPerformed

    private void federalTaxTextTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_federalTaxTextTextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_federalTaxTextTextValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       try {
            Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
            Statement stmt = conn.createStatement();		      
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
              
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountingJFrame().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CarName;
    private java.awt.TextField CarNameText;
    private java.awt.TextField CleaningCostText;
    private javax.swing.JButton CleaningCostbutton;
    private javax.swing.JButton CustomEmployeeConstructor;
    private java.awt.TextField SEDANtext;
    private javax.swing.JButton SUVconstructor;
    private javax.swing.JButton SUVcost;
    private javax.swing.JButton Sedanconstructor;
    private javax.swing.JButton SportCost;
    private java.awt.TextField SportText;
    private java.awt.TextField SuvText;
    private java.awt.TextField employeeNameTextField;
    private javax.swing.JButton federalTaxButton;
    private java.awt.TextField federalTaxText;
    private java.awt.TextField hoursText;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jobHoursButton;
    private javax.swing.JButton jobTitlebutton;
    private java.awt.TextField jobTitletext;
    private javax.swing.JButton monthlyRentButton;
    private java.awt.TextField monthlyRentText;
    private javax.swing.JButton officeCostButton;
    private java.awt.TextField officeCostText;
    private javax.swing.JButton payRateButton;
    private java.awt.TextField payRateText;
    private javax.swing.JButton propertyTaxButton;
    private java.awt.TextField propertyTaxText;
    private javax.swing.JButton salesTaxButton;
    private java.awt.TextField salesTaxText;
    private java.awt.TextField sportsNameField;
    private javax.swing.JButton sportsPriceButton;
    private java.awt.TextField sportsPriceField;
    private javax.swing.JButton sportsconstructor;
    private javax.swing.JButton stateTaxButton;
    private javax.swing.JTextField stateText;
    private javax.swing.JButton techCostButton;
    private java.awt.TextField techCostText;
    private javax.swing.JButton yearlyRentButton;
    private java.awt.TextField yearlyRentText;
    // End of variables declaration//GEN-END:variables
}